help: ## This message listing all useful make targets
	@cat Makefile | grep ' ##' | grep -v "cat Makefile" | sed "s/\(.*\):.*## \(.*\)/\1:\n\t\2/"
prepare: *.sh
	mkdir -pv build

gelf: prepare ## Build the gelf compiler to the build folder
	./gelf gelf.gg build/gelf
	chmod +x build/gelf
	cp build/gelf ./gelf

samples: prepare build/sample-elf build/readfile ## Compile all samples in sample folder. Currently sample-elf and readfile

build/sample-elf: samples/sample-code.gg ## Build the sample-elf.gg that shows some working features
	bash make-elf.sh samples/sample-code.gg build/sample-elf
	chmod +x build/sample-elf

build/readfile: prepare samples/readfile.gg ## Build the readfile.gg file that is a very limited cat clone.
	bash make-elf.sh samples/readfile.gg build/readfile
	chmod +x build/readfile

debugger: prepare debugger/debugger.c ## Build the debugger binary that print all registers changes and syscalls
	make -C debugger build

all: prepare build/gelf samples build/debugger ## Build everithing, gelf compiler, samples and the debugger.

clean: ## Remove the build directory
	rm -fr elf build

check: ## run unit tests
	./tests.sh

qemu-run:
	# https://www.youtube.com/watch?v=u2Juz5sQyYQ
	cp tests/test_hello_world init;
	CPIO_FILE_PATH=./init.cpio;
	echo init | cpio -H newc -o > ${CPIO_FILE_PATH};
	# in kernel linux:
	# make tinyconfig # create a basic .config file
	# cat >> .config <EOF
	# > CONFIG_IRQ_DOMAIN=y
	# CONFIG_IRQ_DOMAIN_HIERARCHY=y
	# CONFIG_GENERIC_IRQ_MATRIX_ALLOCATOR=y
	# CONFIG_GENERIC_CLOCKEVENTS_BROADCAST=y
	# CONFIG_GENERIC_CLOCKEVENTS_BROADCAST_IDLE=y
	# CONFIG_BPF=y
	# CONFIG_ARCH_WANT_DEFAULT_BPF_JIT=y
	# CONFIG_LOG_BUF_SHIFT=17
	# CONFIG_ARCH_SUPPORTS_NUMA_BALANCING=y
	# CONFIG_CC_HAS_INT128=y
	# CONFIG_ARCH_SUPPORTS_INT128=y
	# CONFIG_BLK_DEV_INITRD=y
	# CONFIG_INITRAMFS_SOURCE=""
	# CONFIG_PRINTK=y
	# CONFIG_ELF_CORE=y
	# CONFIG_64BIT=y
	# CONFIG_X86_64=y
	# CONFIG_OUTPUT_FORMAT="elf64-x86-64"
	# CONFIG_ARCH_MMAP_RND_BITS_MIN=28
	# CONFIG_ARCH_MMAP_RND_BITS_MAX=32
	# CONFIG_AUDIT_ARCH=y
	# CONFIG_PGTABLE_LEVELS=5
	# CONFIG_X86_MPPARSE=y
	# CONFIG_GENERIC_CPU=y
	# CONFIG_X86_INTERNODE_CACHE_SHIFT=6
	# CONFIG_X86_L1_CACHE_SHIFT=6
	# CONFIG_X86_MINIMUM_CPU_FAMILY=64
	# CONFIG_HPET_TIMER=y
	# CONFIG_UP_LATE_INIT=y
	# CONFIG_X86_LOCAL_APIC=y
	# CONFIG_X86_IO_APIC=y
	# CONFIG_X86_VSYSCALL_EMULATION=y
	# CONFIG_X86_5LEVEL=y
	# CONFIG_X86_DIRECT_GBPAGES=y
	# CONFIG_ARCH_SPARSEMEM_DEFAULT=y
	# CONFIG_ILLEGAL_POINTER_VALUE=0xdead000000000000
	# CONFIG_X86_CET=y
	# CONFIG_X86_KERNEL_IBT=y
	# CONFIG_X86_INTEL_MEMORY_PROTECTION_KEYS=y
	# CONFIG_ARCH_SUPPORTS_KEXEC_FILE=y
	# CONFIG_ARCH_SUPPORTS_CRASH_DUMP=y
	# CONFIG_DYNAMIC_MEMORY_LAYOUT=y
	# CONFIG_LEGACY_VSYSCALL_XONLY=y
	# CONFIG_HAVE_LIVEPATCH=y
	# CONFIG_FUNCTION_PADDING_CFI=11
	# CONFIG_FUNCTION_PADDING_BYTES=16
	# CONFIG_ARCH_HAS_ADD_PAGES=y
	# CONFIG_HAVE_RUST=y
	# CONFIG_ARCH_SUPPORTS_PROPELLER_CLANG=y
	# CONFIG_ARCH_SUPPORTS_CFI_CLANG=y
	# CONFIG_HAVE_CONTEXT_TRACKING_USER=y
	# CONFIG_HAVE_CONTEXT_TRACKING_USER_OFFSTACK=y
	# CONFIG_HAVE_VIRT_CPU_ACCOUNTING_GEN=y
	# CONFIG_HAVE_ARCH_TRANSPARENT_HUGEPAGE_PUD=y
	# CONFIG_HAVE_ARCH_HUGE_VMAP=y
	# CONFIG_HAVE_ARCH_HUGE_VMALLOC=y
	# CONFIG_HAVE_ARCH_SOFT_DIRTY=y
	# CONFIG_MODULES_USE_ELF_RELA=y
	# CONFIG_HAVE_IRQ_EXIT_ON_IRQ_STACK=y
	# CONFIG_ARCH_MMAP_RND_BITS=28
	# CONFIG_HAVE_OBJTOOL=y
	# CONFIG_HAVE_JUMP_LABEL_HACK=y
	# CONFIG_HAVE_NOINSTR_HACK=y
	# CONFIG_HAVE_NOINSTR_VALIDATION=y
	# CONFIG_HAVE_UACCESS_VALIDATION=y
	# CONFIG_HAVE_STACK_VALIDATION=y
	# CONFIG_HAVE_ARCH_VMAP_STACK=y
	# CONFIG_VMAP_STACK=y
	# CONFIG_HAVE_STATIC_CALL_INLINE=y
	# CONFIG_ARCH_SUPPORTS_PAGE_TABLE_CHECK=y
	# CONFIG_ARCH_HAS_ELFCORE_COMPAT=y
	# CONFIG_ARCH_HAS_NONLEAF_PMD_YOUNG=y
	# CONFIG_FUNCTION_ALIGNMENT_16B=y
	# CONFIG_FUNCTION_ALIGNMENT=16
	# CONFIG_BINFMT_ELF=y
	# CONFIG_ELFCORE=y
	# CONFIG_CORE_DUMP_DEFAULT_ELF_HEADERS=y
	# CONFIG_BINFMT_SCRIPT=y
	# CONFIG_COREDUMP=y
	# CONFIG_SPARSEMEM=y
	# CONFIG_SPARSEMEM_EXTREME=y
	# CONFIG_SPARSEMEM_VMEMMAP_ENABLE=y
	# CONFIG_SPARSEMEM_VMEMMAP=y
	# CONFIG_ARCH_WANT_OPTIMIZE_DAX_VMEMMAP=y
	# CONFIG_ARCH_WANT_OPTIMIZE_HUGETLB_VMEMMAP=y
	# CONFIG_ARCH_ENABLE_MEMORY_HOTPLUG=y
	# CONFIG_ARCH_ENABLE_SPLIT_PMD_PTLOCK=y
	# CONFIG_PHYS_ADDR_T_64BIT=y
	# CONFIG_ARCH_WANTS_THP_SWAP=y
	# CONFIG_ARCH_HAS_PTE_DEVMAP=y
	# CONFIG_ZONE_DMA32=y
	# CONFIG_ARCH_USES_HIGH_VMA_FLAGS=y
	# CONFIG_ARCH_HAS_PKEYS=y
	# CONFIG_ARCH_SUPPORTS_PER_VMA_LOCK=y
	# CONFIG_NET=y
	#
	# CONFIG_MAX_SKB_FRAGS=17
	# CONFIG_NET_RX_BUSY_POLL=y
	#
	#
	# CONFIG_WIRELESS=y
	#
	# CONFIG_MAC80211_STA_HASH_MAX_SIZE=0
	# CONFIG_NET_9P=y
	# CONFIG_NET_9P_FD=y
	# CONFIG_NET_9P_VIRTIO=y
	# CONFIG_FAILOVER=y
	#
	# CONFIG_NETDEVICES=y
	# CONFIG_NET_CORE=y
	# CONFIG_VIRTIO_NET=y
	# CONFIG_ETHERNET=y
	# CONFIG_NET_VENDOR_ALACRITECH=y
	# CONFIG_NET_VENDOR_AMAZON=y
	# CONFIG_NET_VENDOR_AQUANTIA=y
	# CONFIG_NET_VENDOR_ARC=y
	# CONFIG_NET_VENDOR_ASIX=y
	# CONFIG_NET_VENDOR_BROADCOM=y
	# CONFIG_NET_VENDOR_CADENCE=y
	# CONFIG_NET_VENDOR_CAVIUM=y
	# CONFIG_NET_VENDOR_CORTINA=y
	# CONFIG_NET_VENDOR_DAVICOM=y
	# CONFIG_NET_VENDOR_ENGLEDER=y
	# CONFIG_NET_VENDOR_EZCHIP=y
	# CONFIG_NET_VENDOR_FUNGIBLE=y
	# CONFIG_NET_VENDOR_GOOGLE=y
	# CONFIG_NET_VENDOR_HUAWEI=y
	# CONFIG_NET_VENDOR_I825XX=y
	# CONFIG_NET_VENDOR_INTEL=y
	# CONFIG_NET_VENDOR_LITEX=y
	# CONFIG_NET_VENDOR_META=y
	# CONFIG_NET_VENDOR_MICREL=y
	# CONFIG_NET_VENDOR_MICROCHIP=y
	# CONFIG_NET_VENDOR_MICROSEMI=y
	# CONFIG_NET_VENDOR_MICROSOFT=y
	# CONFIG_NET_VENDOR_NI=y
	# CONFIG_NET_VENDOR_NATSEMI=y
	# CONFIG_NET_VENDOR_NETRONOME=y
	# CONFIG_NET_VENDOR_8390=y
	# CONFIG_NET_VENDOR_PENSANDO=y
	# CONFIG_NET_VENDOR_QUALCOMM=y
	# CONFIG_NET_VENDOR_RENESAS=y
	# CONFIG_NET_VENDOR_ROCKER=y
	# CONFIG_NET_VENDOR_SAMSUNG=y
	# CONFIG_NET_VENDOR_SEEQ=y
	# CONFIG_NET_VENDOR_SOLARFLARE=y
	# CONFIG_NET_VENDOR_SOCIONEXT=y
	# CONFIG_NET_VENDOR_STMICRO=y
	# CONFIG_NET_VENDOR_SYNOPSYS=y
	# CONFIG_NET_VENDOR_VERTEXCOM=y
	# CONFIG_NET_VENDOR_VIA=y
	# CONFIG_NET_VENDOR_WANGXUN=y
	# CONFIG_NET_VENDOR_WIZNET=y
	# CONFIG_NET_VENDOR_XILINX=y
	#
	#
	#
	# CONFIG_WLAN=y
	# CONFIG_WLAN_VENDOR_ADMTEK=y
	# CONFIG_WLAN_VENDOR_ATH=y
	# CONFIG_WLAN_VENDOR_ATMEL=y
	# CONFIG_WLAN_VENDOR_BROADCOM=y
	# CONFIG_WLAN_VENDOR_INTEL=y
	# CONFIG_WLAN_VENDOR_INTERSIL=y
	# CONFIG_WLAN_VENDOR_MARVELL=y
	# CONFIG_WLAN_VENDOR_MEDIATEK=y
	# CONFIG_WLAN_VENDOR_MICROCHIP=y
	# CONFIG_WLAN_VENDOR_PURELIFI=y
	# CONFIG_WLAN_VENDOR_RALINK=y
	# CONFIG_WLAN_VENDOR_REALTEK=y
	# CONFIG_WLAN_VENDOR_RSI=y
	# CONFIG_WLAN_VENDOR_SILABS=y
	# CONFIG_WLAN_VENDOR_ST=y
	# CONFIG_WLAN_VENDOR_TI=y
	# CONFIG_WLAN_VENDOR_ZYDAS=y
	# CONFIG_WLAN_VENDOR_QUANTENNA=y
	#
	#
	# CONFIG_NET_FAILOVER=y
	# CONFIG_INPUT=y
	# CONFIG_INPUT_VIVALDIFMAP=y
	#
	#
	# CONFIG_INPUT_KEYBOARD=y
	# CONFIG_KEYBOARD_ATKBD=y
	# CONFIG_INPUT_MOUSE=y
	# CONFIG_MOUSE_PS2=y
	# CONFIG_MOUSE_PS2_ALPS=y
	# CONFIG_MOUSE_PS2_BYD=y
	# CONFIG_MOUSE_PS2_LOGIPS2PP=y
	# CONFIG_MOUSE_PS2_SYNAPTICS=y
	# CONFIG_MOUSE_PS2_CYPRESS=y
	# CONFIG_MOUSE_PS2_TRACKPOINT=y
	# CONFIG_MOUSE_PS2_FOCALTECH=y
	# CONFIG_SERIO=y
	# CONFIG_SERIO_I8042=y
	# CONFIG_SERIO_SERPORT=y
	# CONFIG_SERIO_LIBPS2=y
	# CONFIG_TTY=y
	# CONFIG_VT=y
	# CONFIG_CONSOLE_TRANSLATIONS=y
	# CONFIG_VT_CONSOLE=y
	# CONFIG_UNIX98_PTYS=y
	# CONFIG_LEGACY_PTYS=y
	# CONFIG_LEGACY_PTY_COUNT=256
	# CONFIG_LEGACY_TIOCSTI=y
	# CONFIG_LDISC_AUTOLOAD=y
	#
	#
	#
	# CONFIG_HVC_DRIVER=y
	# CONFIG_VIRTIO_CONSOLE=y
	#
	# CONFIG_VGA_CONSOLE=y
	# CONFIG_DUMMY_CONSOLE=y
	# CONFIG_DUMMY_CONSOLE_COLUMNS=80
	# CONFIG_DUMMY_CONSOLE_ROWS=25
	# CONFIG_HID_SUPPORT=y
	# CONFIG_HID=y
	# CONFIG_HID_GENERIC=y
	#
	#
	#
	# CONFIG_VIRTIO_ANCHOR=y
	# CONFIG_VIRTIO=y
	# CONFIG_NETFS_SUPPORT=y
	# CONFIG_ARCH_HAS_GIGANTIC_PAGE=y
	# CONFIG_NETWORK_FILESYSTEMS=y
	# CONFIG_GENERIC_NET_UTILS=y
	# CONFIG_CRYPTO_LIB_POLY1305_RSIZE=11
	# CONFIG_CRYPTO_LIB_SHA1=y
	# CONFIG_NEED_DMA_MAP_STATE=y
	# CONFIG_ARCH_DMA_ADDR_T_64BIT=y
	# CONFIG_SWIOTLB=y
	# CONFIG_DMA_NEED_SYNC=y
	# CONFIG_NLATTR=y
	# CONFIG_DIMLIB=y
	# CONFIG_VDSO_GETRANDOM=y
	# CONFIG_ARCH_HAS_PMEM_API=y
	# CONFIG_ARCH_HAS_UACCESS_FLUSHCACHE=y
	# CONFIG_ARCH_HAS_COPY_MC=y
	# CONFIG_OBJTOOL=y
	# CONFIG_HAVE_ARCH_KCSAN=y
	# CONFIG_HAVE_ARCH_KASAN=y
	# CONFIG_HAVE_ARCH_KASAN_VMALLOC=y
	# CONFIG_HAVE_ARCH_KMSAN=y
	# CONFIG_HARDLOCKUP_CHECK_TIMESTAMP=y
	# CONFIG_HAVE_DYNAMIC_FTRACE_WITH_ARGS=y
	# CONFIG_HAVE_FENTRY=y
	# CONFIG_HAVE_OBJTOOL_MCOUNT=y
	# CONFIG_HAVE_OBJTOOL_NOP_MCOUNT=y
	# CONFIG_HAVE_SAMPLE_FTRACE_DIRECT=y
	# CONFIG_HAVE_SAMPLE_FTRACE_DIRECT_MULTI=y
	# CONFIG_ARCH_HAS_KCOV=y
	
	# EOF
	# make menuconfig # if want to add features;
	# make -j 30 # use 30 cpu cores to build fast
	# make isoimage FDARGS="initrd=/init.cpio" FDINITRD="${CPIO_FILE_PATH}";
	qemu-system-x86_64 -enable-kvm -cdrom image.iso -m 128M;

gelf-bash: ## compile and load a bash builtin extension
	gcc bash_extension.c \
		-s -ffunction-sections -fdata-sections -Wl,--gc-sections \
	-shared -fPIC -I/usr/include/bash -I/usr/include/bash/include -I/usr/include/bash/builtins -I/usr/lib/bash -I. -o gelf-bash.so
	# to use it, run:
	# enable -d gelf
	# enable -f ./gelf-bash.so gelf
